name: Build & Deploy LLM Docker Image

on:
  push:
    branches:
      - main
      - llm

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. GitHub Repository 체크아웃
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Docker Hub 로그인
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.LLM_DOCKER_USERNAME }}
        password: ${{ secrets.LLM_DOCKERHUB_TOKEN }}

    # 3. Docker 이미지 빌드 및 푸시
    - name: Build and Push Docker Image
      run: |
        docker buildx build --no-cache --push \
          -t ${{ secrets.LLM_DOCKER_USERNAME }}/llm_flask:v1.1 \
          ./LLM/LLM_run
